# Remember to add it in env.production because it is the nextjs project
apiVersion: v1
stringData:
  REDIS_URL: <REDIS_URL>
  DATABASE_URL: <DATABASE_URL>
  SIMPLEHASH_API_KEY: <SIMPLEHASH_API_KEY>
  OPENAI_API_KEY: <OPENAI_API_KEY>
  ANONYMOUS_ACCOUNT_PRIVATEKEY: <ANONYMOUS_ACCOUNT_PRIVATEKEY>
  PORTFOLIO_GITHUB_TOKEN: <PORTFOLIO_GITHUB_TOKEN>
  OTEL_EXPORTER_JAEGER_ENDPOINT: <OTEL_EXPORTER_JAEGER_ENDPOINT>
  OTEL_EXPORTER_JAEGER_PROTOCOL: <OTEL_EXPORTER_JAEGER_PROTOCOL>
kind: Secret
metadata:
  name: xlog
  namespace: crossbell
  annotations:
    avp.kubernetes.io/path: "kv/data/crossbell/xlog"
type: Opaque
