apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: xlog
  namespace: crossbell
spec:
  maxReplicas: 14
  minReplicas: 7
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xlog
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 300
